#!/bin/bash
# dockit: utility to make containers for normal development easy
# This is an early prototype

# stop on any uncaught error
set -e

check_debug() {
    if [ -n "${DOCKIT_DEBUG}" ]; then
        set -x
    fi
}

check_debug

# DOCKIT script path, works for both sides
MY_SCRIPT_NAME=$(basename $0)
MY_SCRIPT_FULL_PATH=$(readlink -f $0)
MY_SCRIPT_DIR=$(dirname $MY_SCRIPT_FULL_PATH)

# Names of vars to be transported to the other side
SAVE_VARS="
DOCKIT_DEBUG
DOCKIT_ACTION
DOCKIT_DISTRO
DOCKIT_BRANCH
DOCKIT_TOP_DIR
DOCKIT_MOUNTDIR
DOCKIT_PRJ_SCRIPT
DOCKIT_REBUILD
DOCKIT_GENERIC
DOCKIT_ISOLATE
DOCKIT_READ_ONLY
DOCKIT_TEMP
MY_USER
MY_UID
MY_GID
OPT_SUDO
"

source $MY_SCRIPT_DIR/common.sh

# These are the lowest priority defaults
set_defaults() {
    # Specify defaults
    : ${DOCKIT_DISTRO:=ubuntu:latest}
    : ${DOCKIT_PRJ_SCRIPT:=.prj/prj_setup.sh}
    : ${DOCKIT_MOUNTDIR:=/prj}
    : ${DOCKIT_BRANCH:=./WORKTREE}
    : ${DOCKIT_TOP_DIR:=.}
    : ${DOCKIT_REBUILD:=false}
    : ${DOCKIT_GENERIC:=false}
    : ${DOCKIT_ISOLATE:=false}
    : ${DOCKIT_READ_ONLY:=false}
    : ${DOCKIT_TEMP:=no}
    : ${DOCKIT_PURGE_GLOBAL:=false}
    : ${MY_UID:=$(id -u)}
    : ${MY_GID:=$(id -g)}
    : ${MY_USER:=$(whoami)}
    # DOCKIT_OLDER_THAN not defined by default

    : ${OPT_SUDO:=yes}
}

top_level() {
    export DISTRO
    export PRJ_SCRIPT
    add_local_gitignore
    #find_container
    local_config
    mktemp
    docker run -it --rm \
        -v "${PWD}:${DOCKIT_MOUNTDIR}" $DISTRO \
        ${MOUNTDIR}/$TMPDIR/$MY_SCRIPT_NAME \
        --std-flow "$@"
}

mktemp() {
    local DISTRO_NAME=${DOCKIT_DISTRO//:/-}     # replace colons with dash

    TMPDIR=.prjinfo/local/${MY_SCRIPT_NAME}-${DISTRO_NAME}
    mkdir -p $TMPDIR

    # make vars file
    TMPFILE=$TMPDIR/vars
    echo "#created automatically by dockit, do not edit" >$TMPFILE
    for v in $SAVE_VARS; do
        echo export $v=${!v} >>$TMPFILE
    done

    TMP1=$(cd . ; dirs +0)  # get project name with ~ for HOME
    TMP1=${TMP1//\~/H}       # replace tidle with 'H'
    TMP1=${TMP1//\//_}      # replace all slashes with underscores
    CONTAINER_NAME=dockit_${TMP1}__${DISTRO_NAME}
    echo $CONTAINER_NAME                    >$TMPDIR/name

    cp $MY_SCRIPT_FULL_PATH $MY_SCRIPT_DIR/common.sh $TMPDIR
}

std_flow() {
    CTRL_DIR=$(cd "$(dirname $0)"; pwd)
    PRJ_DIR=$(cd $CTRL_DIR/../../..; pwd)

    cd ${PRJ_DIR}

    # read vars from TEMPFILE
    source $CTRL_DIR/vars

    # do common admin setup of the container
    setup_distro

    if [ -f "./${PRJ_SCRIPT}" ]; then
        # now execute the command the user specified (or project specific setup)
        ./${PRJ_SCRIPT} admin_setup

        # project specific setup in user context
        su $MY_USER ./${PRJ_SCRIPT} prj_setup

        # project specific build/run, again in user context
        su $MY_USER ./${PRJ_SCRIPT} prj_build
    else
        sudo -iu $MY_USER
    fi
    exit
}

help() {
    echo "usage: dockit [dockit options] <command> [command options]"
    echo "command is one of:"
    echo "build     do the default build command in the container"
    echo "shell     get a shell in the container"
    echo "cmd       do an arbitrary command in the container"
    echo "icmd      do an arbitrary interactive command in the container"
    echo "purge     delete all containers for this project"
    echo ""
    echo "dockit options:"
    echo "--branch          remote/branch"
    echo "                  specify the remote and branch to build"
    echo "                  default ./WORKTREE"
    echo "--distro name     specify the distro"
    echo "--script path     specify the project specific setup script"
    echo "--rebuild         rebuild the container"
    echo "--generic         don't personalize to the user"
    echo "--isolate         don't mount project dir in container"
    echo "--read-only       mount project dir in container as read-only"
    echo "--top-dir dir     specify the top project dir"
    echo "--mount           specify the mount point in the container of the"
    echo "                  top project dir. Can be absolute or relative"
    echo "                  to user's $HOME"
    echo "--temp            delete the container after it has finished"
    echo "--temp-ok         delete the container if the return code is ok"
    echo "--mr-clean        --rebuild --generic --isolate"
    echo ""
    echo "options for purge"
    echo "--older-than N    delete all containers that have not run in N days"
    echo "--global          look at all dockit created containers"
    echo ""
    echo "default options will be loaded from"
    echo "    .prj/local/dockit"
    echo "    .prj/dockit"
    echo "    ~/.prjtool/dockit"
    echo ""
    echo "example:"
    echo "  $ dockit build"
    echo "  $ dockit --distro fedora:rawhide build linux"
    echo "  $ dockit --temp-ok --mr-clean --branch origin/main build"
}

get_dockit_options() {
    SHIFT_COUNT=0
    while true; do
        case "$1" in
        --distro)
            DOCKIT_DISTRO=$2
            shift 2
            SHIFT_COUNT=$(( $SHIFT_COUNT + 2 ))
            ;;
        --script)
            DOCKIT_PRJ_SCRIPT=$2
            shift 2
            SHIFT_COUNT=$(( $SHIFT_COUNT + 2 ))
            ;;
        --branch)
            DOCKIT_BRANCH=$2
            shift 2
            SHIFT_COUNT=$(( $SHIFT_COUNT + 2 ))
            ;;
        --top-dir)
            DOCKIT_TOP_DIR=$2
            shift 2
            SHIFT_COUNT=$(( $SHIFT_COUNT + 2 ))
            ;;
        --rebuild)
            DOCKIT_REBUILD=true
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 1 ))
            ;;
        --generic)
            DOCKIT_GENERIC=true
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 1 ))
            ;;
        --isolate)
            DOCKIT_ISOLATE=true
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 1 ))
            ;;
        --read-only)
            DOCKIT_READ_ONLY=true
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 1 ))
            ;;
        --temp)
            DOCKIT_TEMP=yes
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 1 ))
            ;;
        --temp-ok)
            DOCKIT_TEMP=ok
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 1 ))
            ;;
        --older-than)
            DOCKIT_OLDER_THAN=$2
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 2 ))
            ;;
        --global)
            DOCKIT_PURGE_GLOBAL=true
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 1 ))
            ;;
        --debug)
            DOCKIT_DEBUG=yes
            shift 1
            SHIFT_COUNT=$(( $SHIFT_COUNT + 1 ))
            check_debug
            ;;
        --*)
            echo unknown option "$1"
            exit 2
            ;;
        *)
            return
            ;;
        esac
    done
}

case "$1" in
--std-flow)
    std_flow "$@"
    ;;
*)
    get_dockit_options "$@"; shift $SHIFT_COUNT
    top_level "$@"
    ;;
esac
