#!/bin/bash
# dockit: utility to make containers for normal development easy
# This is an early prototype

set -e

if [ "$1" = "-d" ]; then
    set -x
    shift
fi

MOUNTDIR=/prj
SCRIPT_NAME=$(basename $0)
SCRIPT_FULL_PATH=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT_FULL_PATH)

source $SCRIPT_DIR/common.sh

top_level() {
    get_common_options "$@"
    shift $SHIFT_COUNT

    export DISTRO
    export PRJ_SCRIPT
    add_local_gitignore
    #find_container
    #find_config
    mktemp
    docker run -it --rm \
        -v "${PWD}:${MOUNTDIR}" $DISTRO \
        ${MOUNTDIR}/$TMPDIR/$SCRIPT_NAME \
        --std-flow "$@"
}

std_flow() {
    CTRL_DIR=$(cd "$(dirname $0)"; pwd)
    PRJ_DIR=$(cd $CTRL_DIR/../../..; pwd)

    cd ${PRJ_DIR}

    # read vars from TEMPFILE
    source $CTRL_DIR/vars

    # do common admin setup of the container
    setup_distro

    if [ -f "./${PRJ_SCRIPT}" ]; then
        # now execute the command the user specified (or project specific setup)
        ./${PRJ_SCRIPT} admin_setup

        # project specific setup in user context
        su $MY_USER ./${PRJ_SCRIPT} prj_setup

        # project specific build/run, again in user context
        su $MY_USER ./${PRJ_SCRIPT} prj_build
    else
        sudo -iu $MY_USER
    fi
    exit
}

case "$1" in
--std-flow)
    std_flow "$@"
    ;;
*)
    top_level "$@"
    ;;
esac
