#!/bin/bash

do_venv() {
    . venv/bin/activate
    pip3 install boto3
}

# if fresh boot of container or VM package list will be incomplete and out of data
sudo apt update

sudo apt install python3-pip python3-venv

python3 -m venv venv
(do_venv)

# setup libvirt with qemu and kvm support
sudo apt install -y libvirt-daemon-system libvirt-clients

# setup base vagrant
sudo apt install -y vagrant vagrant-libvirt

# needed for vagrant-aws
sudo apt install -y ruby-dev libxml2-dev libcurl4-openssl-dev

vagrant plugin install vagrant-libvirt
vagrant plugin install vagrant-packet
vagrant plugin install vagrant-aws
vagrant plugin install mutate
vagrant box add bento/ubuntu-18.04 --provider virtualbox
vagrant mutate bento/ubuntu-18.04 --provider libvirt
vagrant box add --force packet.box https://github.com/jeefy/vagrant-packet/raw/master/packet.box
vagrant box add --force dummy_aws https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
